Repository HongDam-org/TWTW, pull requests merged in 2023-09, with the labels that each got.

#12 [FEAT] search map api docs
  backend/src/docs/index.adoc
  backend/src/docs/plan.adoc
  backend/src/test/java/com/twtw/backend/domain/plan/controller/PlanControllerTest.java
  backend/src/test/java/com/twtw/backend/support/docs/RestDocsTest.java
Labels: docs

#16 [FEAT] 빈 등록 단순화 및 properties 적용
  backend/src/main/java/com/twtw/backend/config/client/NaverWebClientConfig.java
  backend/src/main/java/com/twtw/backend/config/client/WebClientConfig.java
  backend/src/main/java/com/twtw/backend/config/mapper/CompositePropertyNamingStrategy.java
  backend/src/main/java/com/twtw/backend/config/mapper/KakaoObjectMapperConfig.java
  backend/src/main/java/com/twtw/backend/config/mapper/ObjectMapperConfig.java
  backend/src/main/java/com/twtw/backend/config/properties/PropertiesConfig.java
  backend/src/main/java/com/twtw/backend/domain/path/client/SearchPathClient.java
  backend/src/main/java/com/twtw/backend/domain/path/service/PathService.java
  backend/src/main/java/com/twtw/backend/domain/plan/client/SearchDestinationClient.java
  backend/src/main/java/com/twtw/backend/global/client/PathClient.java
  backend/src/main/java/com/twtw/backend/global/properties/KakaoProperties.java
  backend/src/main/java/com/twtw/backend/global/properties/NaverProperties.java
Labels: refactor

#19 [DOCS] auth and path api docs
  backend/src/docs/auth.adoc
  backend/src/docs/index.adoc
  backend/src/docs/path.adoc
  backend/src/test/java/com/twtw/backend/domain/member/controller/AuthControllerTest.java
  backend/src/test/java/com/twtw/backend/domain/path/controller/PathControllerTest.java
Labels: docs

#17 [FEAT] tmap api 연동 및 보행자 경로 로직 구현
  backend/build.gradle
  backend/src/main/java/com/twtw/backend/config/properties/PropertiesConfig.java
  backend/src/main/java/com/twtw/backend/config/security/SecurityConfig.java
  backend/src/main/java/com/twtw/backend/domain/path/client/SearchCarPathClient.java
  backend/src/main/java/com/twtw/backend/domain/path/client/SearchPedPathClient.java
  backend/src/main/java/com/twtw/backend/domain/path/controller/PathController.java
  backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/Position.java
  backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/ResponsePositionFormat.java
  backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/RouteUnitEnt.java
  backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/SearchCarPathRequest.java
  backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/SearchCarPathResponse.java
  backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/SearchPathFuel.java
  backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/SearchPathOption.java
  backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/SectionUnit.java
  backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/Summary.java
  backend/src/main/java/com/twtw/backend/domain/path/dto/client/ped/Geometry.java
  backend/src/main/java/com/twtw/backend/domain/path/dto/client/ped/SearchPedPathRequest.java
  backend/src/main/java/com/twtw/backend/domain/path/dto/client/ped/SearchPedPathResponse.java
  backend/src/main/java/com/twtw/backend/domain/path/service/PathService.java
  backend/src/main/java/com/twtw/backend/global/properties/TmapProperties.java
Labels: feat

#20 [FEAT] webclient 구조 수정
  backend/build.gradle
  backend/src/main/java/com/twtw/backend/config/properties/PropertiesConfig.java
  backend/src/main/java/com/twtw/backend/domain/path/client/SearchCarPathClient.java
  backend/src/main/java/com/twtw/backend/domain/path/client/SearchPedPathClient.java
  backend/src/main/java/com/twtw/backend/domain/plan/client/SearchDestinationClient.java
  backend/src/main/java/com/twtw/backend/global/client/KakaoMapClient.java
  backend/src/main/java/com/twtw/backend/global/client/NaverMapClient.java
  backend/src/main/java/com/twtw/backend/global/client/TmapClient.java
Labels: refactor
