Repository HongDam-org/TWTW, pull requests merged in 2023-08, with the labels that each got.

#4 [FEAT] reformat and ci github actions
  .github/workflows/backend-ci.yml
  .github/workflows/reformat-google-java-format.yml
Labels: setting

#5 [FEAT] update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/pull_request_template.yml
Labels: setting

#7 [FEAT] rest docs 세팅
  backend/build.gradle
  backend/src/docs/index.adoc
  backend/src/test/java/com/twtw/backend/support/docs/ApiDocsUtils.java
  backend/src/test/java/com/twtw/backend/support/docs/RestDocsConfig.java
  backend/src/test/java/com/twtw/backend/support/docs/RestDocsTest.java
Labels: docs, setting

#9 [FEAT] 카카오 map api 연동
  .gitignore
  backend/build.gradle
  backend/src/main/java/com/twtw/backend/config/client/WebClientConfig.java
  backend/src/main/java/com/twtw/backend/config/mapper/ObjectMapperConfig.java
  backend/src/main/java/com/twtw/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/twtw/backend/domain/plan/client/SearchDestinationClient.java
  backend/src/main/java/com/twtw/backend/domain/plan/controller/PlanController.java
  backend/src/main/java/com/twtw/backend/domain/plan/dto/client/MetaDetails.java
  backend/src/main/java/com/twtw/backend/domain/plan/dto/client/PlaceDetails.java
  backend/src/main/java/com/twtw/backend/domain/plan/dto/client/SearchDestinationRequest.java
  backend/src/main/java/com/twtw/backend/domain/plan/dto/client/SearchDestinationResponse.java
  backend/src/main/java/com/twtw/backend/domain/plan/dto/response/PlanDestinationResponse.java
  backend/src/main/java/com/twtw/backend/domain/plan/entity/CategoryGroupCode.java
  backend/src/main/java/com/twtw/backend/domain/plan/entity/Plan.java
  backend/src/main/java/com/twtw/backend/domain/plan/entity/PlanMember.java
  backend/src/main/java/com/twtw/backend/domain/plan/entity/PlanPlace.java
  backend/src/main/java/com/twtw/backend/domain/plan/repository/PlanRepository.java
  backend/src/main/java/com/twtw/backend/domain/plan/service/PlanService.java
  backend/src/main/java/com/twtw/backend/global/client/MapClient.java
  backend/src/main/java/com/twtw/backend/global/exception/WebClientResponseException.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/twtw/backend/BackendApplicationTests.java
Labels: feat

#10 [FEAT] naver maps api
  backend/src/main/java/com/twtw/backend/config/client/KakaoWebClientConfig.java
  backend/src/main/java/com/twtw/backend/config/client/NaverWebClientConfig.java
  backend/src/main/java/com/twtw/backend/config/security/SecurityConfig.java
  backend/src/main/java/com/twtw/backend/domain/SwaggerConfiguration.java
  backend/src/main/java/com/twtw/backend/domain/path/client/SearchPathClient.java
  backend/src/main/java/com/twtw/backend/domain/path/controller/PathController.java
  backend/src/main/java/com/twtw/backend/domain/path/dto/client/SearchPathFuel.java
  backend/src/main/java/com/twtw/backend/domain/path/dto/client/SearchPathOption.java
  backend/src/main/java/com/twtw/backend/domain/path/dto/client/SearchPathRequest.java
  backend/src/main/java/com/twtw/backend/domain/path/dto/client/SearchPathResponse.java
  backend/src/main/java/com/twtw/backend/domain/path/service/PathService.java
  backend/src/main/java/com/twtw/backend/domain/plan/client/SearchDestinationClient.java
  backend/src/main/java/com/twtw/backend/global/client/PathClient.java
Labels: feat
